apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app 
          image: markpollack/spring-sample-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: url
          - name: POSTGRES_USR
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: username
          - name: POSTGRES_PW
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: password
          envFrom:
            - configMapRef:
                name: spring-configmap-env
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
