kind: Service
apiVersion: v1
metadata:
  name: service
  labels:
    app: rollouts-demo
spec:
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-demo
  type: ClusterIP
  
