apiVersion: v1
kind: Service
metadata:
  name: stable-svc
spec:
  ports:
  - name: 80-8080
    port: 80
    targetPort: 8080
  selector:
    name: app
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  ports:
  - name: 80-8080
    port: 80
    targetPort: 8080
  selector:
    name: app


